### PR TITLE
flexzy2011

### PR DESCRIPTION
**Pull request by flexzy2011**
Hello Jon, In this project(MUI-Booking-App) the top las vegas tours for view the casino image is not showing. I would love to fix that and this will make it my first open source contribution to open source. thanks

### CODE REVIEW

**Comment by mathcodes** [comment]
You're welcome to this if you're still down!

**Comment by mathcodes** [comment]
Let me know!

**Comment by flexzy2011** [comment]
Yes sir, I’m still interested I’ll look it up

**Comment by flexzy2011** [comment]
Hello Jon I’ve fixed it..

**Pull request closed without merging**
